# syntax=docker/dockerfile:1

FROM debian:12

EXPOSE 443 80

VOLUME /config

RUN apt-get update \
    && apt-get install -y ca-certificates openssl fdisk mergerfs snapraid avahi-daemon avahi-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY build/* ./
COPY static ./static

CMD ["./cosmos"]
