# syntax=docker/dockerfile:1

FROM --platform=linux/arm64 arm64v8/debian:11

EXPOSE 443 80

VOLUME /config

RUN apt-get clean
RUN apt-get update 
RUN apt-get install -y ca-certificates openssl

WORKDIR /app

COPY build/cosmos build/cosmos_gray.png build/Logo.png build/GeoLite2-Country.mmdb build/meta.json ./
COPY static ./static

CMD ["./cosmos"]
