package storage 

import (
	"os"
	"os/exec"
	"bytes"
	"strings"
	"fmt"
	
	"github.com/azukaar/cosmos-server/src/utils"
)

const sambaSharePrefix = "cosmos_"
const cosmosSambaConf = "/etc/samba/cosmos-shares.conf"
const mainSambaConf = "/etc/samba/smb.conf"
const sambaIncludeLine = "include = " + cosmosSambaConf

func ensureSambaInclude() error {
    content, err := os.ReadFile(mainSambaConf)
    if err != nil {
        return fmt.Errorf("failed to read smb.conf: %w", err)
    }

    if strings.Contains(string(content), sambaIncludeLine) {
        return nil
    }

    utils.Log("[RemoteStorage] [SAMBA] Adding Cosmos include to smb.conf")

    f, err := os.OpenFile(mainSambaConf, os.O_APPEND|os.O_WRONLY, 0644)
    if err != nil {
        return fmt.Errorf("failed to open smb.conf for writing: %w", err)
    }
    defer f.Close()

    if _, err := f.WriteString("\n" + sambaIncludeLine + "\n"); err != nil {
        return fmt.Errorf("failed to write include line: %w", err)
    }

    return nil
}

func ensureSambaUser(user, pass string) error {
    // Check if user exists
    _, err := utils.Exec("id", user)
    if err != nil {
        // User doesn't exist, create it
        utils.Log(fmt.Sprintf("[RemoteStorage] [SAMBA] Creating system user %s", user))
        _, err = utils.Exec("useradd", "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", user)
        if err != nil {
            return fmt.Errorf("failed to create user: %w", err)
        }
        
        // Set Linux password to unlock the account
        utils.Debug(fmt.Sprintf("[RemoteStorage] [SAMBA] Setting Linux password for user %s", user))
        cmd := exec.Command("chpasswd")
        cmd.Stdin = strings.NewReader(user + ":" + pass + "\n")
        if err := cmd.Run(); err != nil {
            return fmt.Errorf("failed to set Linux password: %w", err)
        }
    }

    // Set samba password
    utils.Debug(fmt.Sprintf("[RemoteStorage] [SAMBA] Setting samba password for user %s", user))
    cmd := exec.Command("smbpasswd", "-a", "-s", user)
    var stderr bytes.Buffer
    cmd.Stderr = &stderr
    cmd.Stdin = strings.NewReader(pass + "\n" + pass + "\n")
    if err := cmd.Run(); err != nil {
        return fmt.Errorf("failed to set samba password: %w, stderr: %s", err, stderr.String())
    }
    utils.Debug(fmt.Sprintf("[RemoteStorage] [SAMBA] Successfully set samba password for user %s", user))

    return nil
}

func startSambaShare(share utils.LocationRemoteStorageConfig) error {
    user := share.Settings["user"]
    pass := share.Settings["pass"]

    // Ensure include line exists
    if err := ensureSambaInclude(); err != nil {
        return err
    }

    if user == "" || pass == "" {
        return fmt.Errorf("samba share requires user and pass")
    }

    // Ensure user exists and has samba password set
    if err := ensureSambaUser(user, pass); err != nil {
        return err
    }

    return nil
}

func writeCosmosSambaShares(shares []utils.LocationRemoteStorageConfig) error {
    var buf bytes.Buffer
    buf.WriteString("# Auto-generated by Cosmos - DO NOT EDIT\n\n")

    for _, share := range shares {
        if share.Protocol != "smb" && share.Protocol != "samba" {
            continue
        }

        user := share.Settings["user"]
        if user == "" {
            continue
        }

        readOnly := "no"
        if perm, ok := share.Settings["permission"]; ok && perm == "R" {
            readOnly = "yes"
        }

        forceUser := ""
        if fu, ok := share.Settings["force user"]; ok && fu != "" {
            forceUser = fu
        }

        shareName := sambaSharePrefix + share.Name
        fmt.Fprintf(&buf, "[%s]\n", shareName)
        fmt.Fprintf(&buf, "   path = %s\n", share.Target)
        fmt.Fprintf(&buf, "   browseable = yes\n")
        fmt.Fprintf(&buf, "   read only = %s\n", readOnly)
        fmt.Fprintf(&buf, "   valid users = %s\n", user)
        if forceUser != "" {
            fmt.Fprintf(&buf, "   force user = %s\n", forceUser)
        }
        fmt.Fprintf(&buf, "   guest ok = no\n")
        buf.WriteString("\n")
    }

    if err := os.WriteFile(cosmosSambaConf, buf.Bytes(), 0644); err != nil {
        return err
    }

    return nil
}

func cleanupCosmosSambaShares() error {
    // Write empty config
    if err := os.WriteFile(cosmosSambaConf, []byte("# Auto-generated by Cosmos - DO NOT EDIT\n"), 0644); err != nil {
        return err
    }
	
    return nil
}
